### ISSUE TITLE
Update runtime to 3.36

### ISSUE THREAD

**Issue by HugLifeTiZ** [flathub/io.github.quodlibet.ExFalso#1]
Hiya. I saw Quod Libet got updated in the updated apps section of Flathub, to use the GNOME 3.36 runtime. The standalone Ex Falso flatpak also needs this update so I can get rid of runtime 3.34. Thank you! :)

**Comment by lazka** [comment]
I'll look into it :)

**Comment by lazka** [comment]
Fixed in #2
