### ISSUE TITLE
Update GNOME platform runtime

### ISSUE THREAD

**Issue by NoTuxNoBux** [flathub/io.github.quodlibet.ExFalso#5]
Hello

Thanks for this Flatpak! Recently, I'm getting this message from flatpak CLI:

```
Info: org.gnome.Platform//3.38 is end-of-life, with reason:
   The GNOME 3.38 runtime is no longer supported as of August 19, 2021. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   io.github.quodlibet.ExFalso
```

Nothing's broken, but just wanted to give you a heads up - it might not be possible or easy to upgrade as-is to another platform. I don't use it, but it might also affect the QuodLibet Flatpak.

**Comment by lazka** [comment]
Thanks, I'll have a look.
